### ISSUE TITLE
--cell parameter error

### ISSUE THREAD

**Issue by Phorbol** [deepmodeling/reacnetgenerator#2160]
根据提供的-h说明，不能很好的确认-c需要的参数格式，可以给出一个默认的--cell参数格式示例么？我在命令行使用
[ [22, 0, 0],
  [0, 22, 0].
  [0, 0, 22] ]
程序并不能读入这种格式

**Comment by Eipgen** [comment]
https://github.com/deepmodeling/reacnetgenerator/blob/52d6d31b13c3d4ae63d6ed40d12c355c8ac4d3d0/reacnetgenerator/reacnetgen.py#L236

you can specify cell like `-c 10 10 10` or `-c 10 0 0 0 10 0 0 0 10`
