### ISSUE TITLE
Question about analysizing reactions in polyaromatic hydrocarbon systems

### ISSUE THREAD

**Issue by SixuanMi** [deepmodeling/reacnetgenerator#2165]
Hi, I have performed molecular dynamics simulations of a PAH system using DeepMD in combination with LAMMPS, and using ReacNetGenerator for reaction network analysis, I found a lot of strange reactions as shown in the screenshot. May I ask why this is happening? Thank you.
![image](https://github.com/deepmodeling/reacnetgenerator/assets/163138892/f4e629e0-34f4-4d35-8965-3b6667c2888a)

**Comment by njzjz** [comment]
The CLI argument `--miso 1` might be helpful in this case. The explanation is in #1563.

**Comment by SixuanMi** [comment]
Thank you. The problem is partialy solved and most of the unreasonable structures are removed. I noticed that --miso 1 could "merge the isomers with same atoms and same bond-network but different bond levels", but these species still exist, such as 10, 12 and 17; 9 and 16; 11 and 15; 7 and 20. And the highest frequency one might has the wrong degree of unsaturation SMILES. May I ask how to solve  this problem? Thank you very much. 
![image](https://github.com/deepmodeling/reacnetgenerator/assets/163138892/1858d1ba-48aa-40c2-b93f-05a40f509f29)

**Comment by njzjz** [comment]
> Thank you. The problem is partialy solved and most of the unreasonable structures are removed. I noticed that --miso 1 could "merge the isomers with same atoms and same bond-network but different bond levels", but these species still exist, such as 10, 12 and 17; 9 and 16; 11 and 15; 7 and 20. And the highest frequency one might has the wrong degree of unsaturation SMILES. May I ask how to solve this problem? Thank you very much.

I marked this as a bug and will review #1563 further. I guess a `sort` is missing somewhere. It would be helpful for debug if you could share something that could reproduce it.

**Comment by SixuanMi** [comment]
Thanks. Part of the trajectory is here. [traj.7z.zip](https://github.com/deepmodeling/reacnetgenerator/files/14581340/traj.7z.zip)

**Comment by SixuanMi** [comment]
Part of the trafectory is sent to your email [jinzhe.zeng@rutgers.edu](mailto:jinzhe.zeng@rutgers.edu)
